// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/filetransfer.proto

package filetransfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation_Type int32

const (
	Operation_CREATE Operation_Type = 0
	Operation_APPEND Operation_Type = 1
	Operation_DELETE Operation_Type = 2
)

// Enum value maps for Operation_Type.
var (
	Operation_Type_name = map[int32]string{
		0: "CREATE",
		1: "APPEND",
		2: "DELETE",
	}
	Operation_Type_value = map[string]int32{
		"CREATE": 0,
		"APPEND": 1,
		"DELETE": 2,
	}
)

func (x Operation_Type) Enum() *Operation_Type {
	p := new(Operation_Type)
	*p = x
	return p
}

func (x Operation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_filetransfer_proto_enumTypes[0].Descriptor()
}

func (Operation_Type) Type() protoreflect.EnumType {
	return &file_proto_filetransfer_proto_enumTypes[0]
}

func (x Operation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation_Type.Descriptor instead.
func (Operation_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{10, 0}
}

// Streaming chunk message for large file transfers
type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FileChunk_Metadata
	//	*FileChunk_Chunk
	Data          isFileChunk_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_filetransfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetData() isFileChunk_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*FileChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *FileChunk) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*FileChunk_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isFileChunk_Data interface {
	isFileChunk_Data()
}

type FileChunk_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // First message contains metadata
}

type FileChunk_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // Subsequent messages contain file chunks
}

func (*FileChunk_Metadata) isFileChunk_Data() {}

func (*FileChunk_Chunk) isFileChunk_Data() {}

type FileMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ClientId          int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OperationId       int64                  `protobuf:"varint,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SourceNodeId      string                 `protobuf:"bytes,4,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	DestinationNodeId string                 `protobuf:"bytes,5,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	OwnerNodeId       string                 `protobuf:"bytes,6,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	TotalSize         int64                  `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`            // Total file size for progress tracking
	Checksum          string                 `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`                                // MD5 checksum for integrity verification
	OperationType     string                 `protobuf:"bytes,9,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"` // "create", "append", "replicate"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_filetransfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *FileMetadata) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *FileMetadata) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *FileMetadata) GetDestinationNodeId() string {
	if x != nil {
		return x.DestinationNodeId
	}
	return ""
}

func (x *FileMetadata) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

func (x *FileMetadata) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileMetadata) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FileMetadata) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

// File operation requests and responses
type CreateFileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data              []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ClientId          int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OperationId       int64                  `protobuf:"varint,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SourceNodeId      string                 `protobuf:"bytes,5,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	DestinationNodeId string                 `protobuf:"bytes,6,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	OwnerNodeId       string                 `protobuf:"bytes,7,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_proto_filetransfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateFileRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateFileRequest) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *CreateFileRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *CreateFileRequest) GetDestinationNodeId() string {
	if x != nil {
		return x.DestinationNodeId
	}
	return ""
}

func (x *CreateFileRequest) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_proto_filetransfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateFileResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type AppendFileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data              []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ClientId          int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OperationId       int64                  `protobuf:"varint,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	SourceNodeId      string                 `protobuf:"bytes,5,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	DestinationNodeId string                 `protobuf:"bytes,6,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	OwnerNodeId       string                 `protobuf:"bytes,7,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendFileRequest) Reset() {
	*x = AppendFileRequest{}
	mi := &file_proto_filetransfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendFileRequest) ProtoMessage() {}

func (x *AppendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendFileRequest.ProtoReflect.Descriptor instead.
func (*AppendFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{4}
}

func (x *AppendFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AppendFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppendFileRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *AppendFileRequest) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *AppendFileRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *AppendFileRequest) GetDestinationNodeId() string {
	if x != nil {
		return x.DestinationNodeId
	}
	return ""
}

func (x *AppendFileRequest) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

type AppendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendFileResponse) Reset() {
	*x = AppendFileResponse{}
	mi := &file_proto_filetransfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendFileResponse) ProtoMessage() {}

func (x *AppendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendFileResponse.ProtoReflect.Descriptor instead.
func (*AppendFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{5}
}

func (x *AppendFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AppendFileResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetFileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ClientId          int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SourceNodeId      string                 `protobuf:"bytes,3,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	DestinationNodeId string                 `protobuf:"bytes,4,opt,name=destination_node_id,json=destinationNodeId,proto3" json:"destination_node_id,omitempty"`
	OwnerNodeId       string                 `protobuf:"bytes,5,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_filetransfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetFileRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetFileRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *GetFileRequest) GetDestinationNodeId() string {
	if x != nil {
		return x.DestinationNodeId
	}
	return ""
}

func (x *GetFileRequest) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_filetransfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetFileResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Replication messages
type ReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_proto_filetransfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicationRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReplicationRequest) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ReplicationRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type ReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationResponse) Reset() {
	*x = ReplicationResponse{}
	mi := &file_proto_filetransfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationResponse) ProtoMessage() {}

func (x *ReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationResponse.ProtoReflect.Descriptor instead.
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Operation_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=hydfs.Operation_Type" json:"type,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OperationId   int64                  `protobuf:"varint,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_proto_filetransfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_filetransfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_filetransfer_proto_rawDescGZIP(), []int{10}
}

func (x *Operation) GetType() Operation_Type {
	if x != nil {
		return x.Type
	}
	return Operation_CREATE
}

func (x *Operation) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Operation) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Operation) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Operation) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *Operation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_filetransfer_proto protoreflect.FileDescriptor

const file_proto_filetransfer_proto_rawDesc = "" +
	"\n" +
	"\x18proto/filetransfer.proto\x12\x05hydfs\"^\n" +
	"\tFileChunk\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.hydfs.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xc6\x02\n" +
	"\fFileMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\x03R\voperationId\x12$\n" +
	"\x0esource_node_id\x18\x04 \x01(\tR\fsourceNodeId\x12.\n" +
	"\x13destination_node_id\x18\x05 \x01(\tR\x11destinationNodeId\x12\"\n" +
	"\rowner_node_id\x18\x06 \x01(\tR\vownerNodeId\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x03R\ttotalSize\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\tR\bchecksum\x12%\n" +
	"\x0eoperation_type\x18\t \x01(\tR\roperationType\"\xfd\x01\n" +
	"\x11CreateFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\x12!\n" +
	"\foperation_id\x18\x04 \x01(\x03R\voperationId\x12$\n" +
	"\x0esource_node_id\x18\x05 \x01(\tR\fsourceNodeId\x12.\n" +
	"\x13destination_node_id\x18\x06 \x01(\tR\x11destinationNodeId\x12\"\n" +
	"\rowner_node_id\x18\a \x01(\tR\vownerNodeId\"^\n" +
	"\x12CreateFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xfd\x01\n" +
	"\x11AppendFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\x12!\n" +
	"\foperation_id\x18\x04 \x01(\x03R\voperationId\x12$\n" +
	"\x0esource_node_id\x18\x05 \x01(\tR\fsourceNodeId\x12.\n" +
	"\x13destination_node_id\x18\x06 \x01(\tR\x11destinationNodeId\x12\"\n" +
	"\rowner_node_id\x18\a \x01(\tR\vownerNodeId\"^\n" +
	"\x12AppendFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xc3\x01\n" +
	"\x0eGetFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12$\n" +
	"\x0esource_node_id\x18\x03 \x01(\tR\fsourceNodeId\x12.\n" +
	"\x13destination_node_id\x18\x04 \x01(\tR\x11destinationNodeId\x12\"\n" +
	"\rowner_node_id\x18\x05 \x01(\tR\vownerNodeId\"o\n" +
	"\x0fGetFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"}\n" +
	"\x12ReplicationRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12.\n" +
	"\toperation\x18\x02 \x01(\v2\x10.hydfs.OperationR\toperation\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\"E\n" +
	"\x13ReplicationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf0\x01\n" +
	"\tOperation\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.hydfs.Operation.TypeR\x04type\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12!\n" +
	"\foperation_id\x18\x05 \x01(\x03R\voperationId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"*\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06APPEND\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\xb0\x04\n" +
	"\x13FileTransferService\x12A\n" +
	"\n" +
	"CreateFile\x12\x18.hydfs.CreateFileRequest\x1a\x19.hydfs.CreateFileResponse\x12A\n" +
	"\n" +
	"AppendFile\x12\x18.hydfs.AppendFileRequest\x1a\x19.hydfs.AppendFileResponse\x128\n" +
	"\aGetFile\x12\x15.hydfs.GetFileRequest\x1a\x16.hydfs.GetFileResponse\x12A\n" +
	"\x10CreateFileStream\x12\x10.hydfs.FileChunk\x1a\x19.hydfs.CreateFileResponse(\x01\x12A\n" +
	"\x10AppendFileStream\x12\x10.hydfs.FileChunk\x1a\x19.hydfs.AppendFileResponse(\x01\x12:\n" +
	"\rGetFileStream\x12\x15.hydfs.GetFileRequest\x1a\x10.hydfs.FileChunk0\x01\x12K\n" +
	"\x12ReplicateOperation\x12\x19.hydfs.ReplicationRequest\x1a\x1a.hydfs.ReplicationResponse\x12J\n" +
	"\x18ReplicateOperationStream\x12\x10.hydfs.FileChunk\x1a\x1a.hydfs.ReplicationResponse(\x01B\x11Z\x0f./;filetransferb\x06proto3"

var (
	file_proto_filetransfer_proto_rawDescOnce sync.Once
	file_proto_filetransfer_proto_rawDescData []byte
)

func file_proto_filetransfer_proto_rawDescGZIP() []byte {
	file_proto_filetransfer_proto_rawDescOnce.Do(func() {
		file_proto_filetransfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_filetransfer_proto_rawDesc), len(file_proto_filetransfer_proto_rawDesc)))
	})
	return file_proto_filetransfer_proto_rawDescData
}

var file_proto_filetransfer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_filetransfer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_filetransfer_proto_goTypes = []any{
	(Operation_Type)(0),         // 0: hydfs.Operation.Type
	(*FileChunk)(nil),           // 1: hydfs.FileChunk
	(*FileMetadata)(nil),        // 2: hydfs.FileMetadata
	(*CreateFileRequest)(nil),   // 3: hydfs.CreateFileRequest
	(*CreateFileResponse)(nil),  // 4: hydfs.CreateFileResponse
	(*AppendFileRequest)(nil),   // 5: hydfs.AppendFileRequest
	(*AppendFileResponse)(nil),  // 6: hydfs.AppendFileResponse
	(*GetFileRequest)(nil),      // 7: hydfs.GetFileRequest
	(*GetFileResponse)(nil),     // 8: hydfs.GetFileResponse
	(*ReplicationRequest)(nil),  // 9: hydfs.ReplicationRequest
	(*ReplicationResponse)(nil), // 10: hydfs.ReplicationResponse
	(*Operation)(nil),           // 11: hydfs.Operation
}
var file_proto_filetransfer_proto_depIdxs = []int32{
	2,  // 0: hydfs.FileChunk.metadata:type_name -> hydfs.FileMetadata
	11, // 1: hydfs.ReplicationRequest.operation:type_name -> hydfs.Operation
	0,  // 2: hydfs.Operation.type:type_name -> hydfs.Operation.Type
	3,  // 3: hydfs.FileTransferService.CreateFile:input_type -> hydfs.CreateFileRequest
	5,  // 4: hydfs.FileTransferService.AppendFile:input_type -> hydfs.AppendFileRequest
	7,  // 5: hydfs.FileTransferService.GetFile:input_type -> hydfs.GetFileRequest
	1,  // 6: hydfs.FileTransferService.CreateFileStream:input_type -> hydfs.FileChunk
	1,  // 7: hydfs.FileTransferService.AppendFileStream:input_type -> hydfs.FileChunk
	7,  // 8: hydfs.FileTransferService.GetFileStream:input_type -> hydfs.GetFileRequest
	9,  // 9: hydfs.FileTransferService.ReplicateOperation:input_type -> hydfs.ReplicationRequest
	1,  // 10: hydfs.FileTransferService.ReplicateOperationStream:input_type -> hydfs.FileChunk
	4,  // 11: hydfs.FileTransferService.CreateFile:output_type -> hydfs.CreateFileResponse
	6,  // 12: hydfs.FileTransferService.AppendFile:output_type -> hydfs.AppendFileResponse
	8,  // 13: hydfs.FileTransferService.GetFile:output_type -> hydfs.GetFileResponse
	4,  // 14: hydfs.FileTransferService.CreateFileStream:output_type -> hydfs.CreateFileResponse
	6,  // 15: hydfs.FileTransferService.AppendFileStream:output_type -> hydfs.AppendFileResponse
	1,  // 16: hydfs.FileTransferService.GetFileStream:output_type -> hydfs.FileChunk
	10, // 17: hydfs.FileTransferService.ReplicateOperation:output_type -> hydfs.ReplicationResponse
	10, // 18: hydfs.FileTransferService.ReplicateOperationStream:output_type -> hydfs.ReplicationResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_filetransfer_proto_init() }
func file_proto_filetransfer_proto_init() {
	if File_proto_filetransfer_proto != nil {
		return
	}
	file_proto_filetransfer_proto_msgTypes[0].OneofWrappers = []any{
		(*FileChunk_Metadata)(nil),
		(*FileChunk_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_filetransfer_proto_rawDesc), len(file_proto_filetransfer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_filetransfer_proto_goTypes,
		DependencyIndexes: file_proto_filetransfer_proto_depIdxs,
		EnumInfos:         file_proto_filetransfer_proto_enumTypes,
		MessageInfos:      file_proto_filetransfer_proto_msgTypes,
	}.Build()
	File_proto_filetransfer_proto = out.File
	file_proto_filetransfer_proto_goTypes = nil
	file_proto_filetransfer_proto_depIdxs = nil
}
