// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: proto/filetransfer.proto

package filetransfer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileTransferService_CreateFile_FullMethodName               = "/hydfs.FileTransferService/CreateFile"
	FileTransferService_AppendFile_FullMethodName               = "/hydfs.FileTransferService/AppendFile"
	FileTransferService_GetFile_FullMethodName                  = "/hydfs.FileTransferService/GetFile"
	FileTransferService_CreateFileStream_FullMethodName         = "/hydfs.FileTransferService/CreateFileStream"
	FileTransferService_AppendFileStream_FullMethodName         = "/hydfs.FileTransferService/AppendFileStream"
	FileTransferService_GetFileStream_FullMethodName            = "/hydfs.FileTransferService/GetFileStream"
	FileTransferService_ReplicateOperation_FullMethodName       = "/hydfs.FileTransferService/ReplicateOperation"
	FileTransferService_ReplicateOperationStream_FullMethodName = "/hydfs.FileTransferService/ReplicateOperationStream"
)

// FileTransferServiceClient is the client API for FileTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FileTransferService handles file data operations between nodes
type FileTransferServiceClient interface {
	// Core file operations that involve actual data transfer
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	AppendFile(ctx context.Context, in *AppendFileRequest, opts ...grpc.CallOption) (*AppendFileResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	// Streaming operations for large files (>4MB)
	CreateFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, CreateFileResponse], error)
	AppendFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, AppendFileResponse], error)
	GetFileStream(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// File replication operations (involve data transfer between nodes)
	ReplicateOperation(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error)
	ReplicateOperationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, ReplicationResponse], error)
}

type fileTransferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileTransferServiceClient(cc grpc.ClientConnInterface) FileTransferServiceClient {
	return &fileTransferServiceClient{cc}
}

func (c *fileTransferServiceClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, FileTransferService_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferServiceClient) AppendFile(ctx context.Context, in *AppendFileRequest, opts ...grpc.CallOption) (*AppendFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendFileResponse)
	err := c.cc.Invoke(ctx, FileTransferService_AppendFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, FileTransferService_GetFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferServiceClient) CreateFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, CreateFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileTransferService_ServiceDesc.Streams[0], FileTransferService_CreateFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, CreateFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_CreateFileStreamClient = grpc.ClientStreamingClient[FileChunk, CreateFileResponse]

func (c *fileTransferServiceClient) AppendFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, AppendFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileTransferService_ServiceDesc.Streams[1], FileTransferService_AppendFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, AppendFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_AppendFileStreamClient = grpc.ClientStreamingClient[FileChunk, AppendFileResponse]

func (c *fileTransferServiceClient) GetFileStream(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileTransferService_ServiceDesc.Streams[2], FileTransferService_GetFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetFileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_GetFileStreamClient = grpc.ServerStreamingClient[FileChunk]

func (c *fileTransferServiceClient) ReplicateOperation(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationResponse)
	err := c.cc.Invoke(ctx, FileTransferService_ReplicateOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferServiceClient) ReplicateOperationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, ReplicationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileTransferService_ServiceDesc.Streams[3], FileTransferService_ReplicateOperationStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, ReplicationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_ReplicateOperationStreamClient = grpc.ClientStreamingClient[FileChunk, ReplicationResponse]

// FileTransferServiceServer is the server API for FileTransferService service.
// All implementations must embed UnimplementedFileTransferServiceServer
// for forward compatibility.
//
// FileTransferService handles file data operations between nodes
type FileTransferServiceServer interface {
	// Core file operations that involve actual data transfer
	CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	AppendFile(context.Context, *AppendFileRequest) (*AppendFileResponse, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	// Streaming operations for large files (>4MB)
	CreateFileStream(grpc.ClientStreamingServer[FileChunk, CreateFileResponse]) error
	AppendFileStream(grpc.ClientStreamingServer[FileChunk, AppendFileResponse]) error
	GetFileStream(*GetFileRequest, grpc.ServerStreamingServer[FileChunk]) error
	// File replication operations (involve data transfer between nodes)
	ReplicateOperation(context.Context, *ReplicationRequest) (*ReplicationResponse, error)
	ReplicateOperationStream(grpc.ClientStreamingServer[FileChunk, ReplicationResponse]) error
	mustEmbedUnimplementedFileTransferServiceServer()
}

// UnimplementedFileTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileTransferServiceServer struct{}

func (UnimplementedFileTransferServiceServer) CreateFile(context.Context, *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedFileTransferServiceServer) AppendFile(context.Context, *AppendFileRequest) (*AppendFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendFile not implemented")
}
func (UnimplementedFileTransferServiceServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFileTransferServiceServer) CreateFileStream(grpc.ClientStreamingServer[FileChunk, CreateFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CreateFileStream not implemented")
}
func (UnimplementedFileTransferServiceServer) AppendFileStream(grpc.ClientStreamingServer[FileChunk, AppendFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AppendFileStream not implemented")
}
func (UnimplementedFileTransferServiceServer) GetFileStream(*GetFileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetFileStream not implemented")
}
func (UnimplementedFileTransferServiceServer) ReplicateOperation(context.Context, *ReplicationRequest) (*ReplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateOperation not implemented")
}
func (UnimplementedFileTransferServiceServer) ReplicateOperationStream(grpc.ClientStreamingServer[FileChunk, ReplicationResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReplicateOperationStream not implemented")
}
func (UnimplementedFileTransferServiceServer) mustEmbedUnimplementedFileTransferServiceServer() {}
func (UnimplementedFileTransferServiceServer) testEmbeddedByValue()                             {}

// UnsafeFileTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileTransferServiceServer will
// result in compilation errors.
type UnsafeFileTransferServiceServer interface {
	mustEmbedUnimplementedFileTransferServiceServer()
}

func RegisterFileTransferServiceServer(s grpc.ServiceRegistrar, srv FileTransferServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileTransferService_ServiceDesc, srv)
}

func _FileTransferService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTransferService_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServiceServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransferService_AppendFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServiceServer).AppendFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTransferService_AppendFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServiceServer).AppendFile(ctx, req.(*AppendFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransferService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTransferService_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransferService_CreateFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransferServiceServer).CreateFileStream(&grpc.GenericServerStream[FileChunk, CreateFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_CreateFileStreamServer = grpc.ClientStreamingServer[FileChunk, CreateFileResponse]

func _FileTransferService_AppendFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransferServiceServer).AppendFileStream(&grpc.GenericServerStream[FileChunk, AppendFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_AppendFileStreamServer = grpc.ClientStreamingServer[FileChunk, AppendFileResponse]

func _FileTransferService_GetFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileTransferServiceServer).GetFileStream(m, &grpc.GenericServerStream[GetFileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_GetFileStreamServer = grpc.ServerStreamingServer[FileChunk]

func _FileTransferService_ReplicateOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServiceServer).ReplicateOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileTransferService_ReplicateOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServiceServer).ReplicateOperation(ctx, req.(*ReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransferService_ReplicateOperationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransferServiceServer).ReplicateOperationStream(&grpc.GenericServerStream[FileChunk, ReplicationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileTransferService_ReplicateOperationStreamServer = grpc.ClientStreamingServer[FileChunk, ReplicationResponse]

// FileTransferService_ServiceDesc is the grpc.ServiceDesc for FileTransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileTransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hydfs.FileTransferService",
	HandlerType: (*FileTransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFile",
			Handler:    _FileTransferService_CreateFile_Handler,
		},
		{
			MethodName: "AppendFile",
			Handler:    _FileTransferService_AppendFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _FileTransferService_GetFile_Handler,
		},
		{
			MethodName: "ReplicateOperation",
			Handler:    _FileTransferService_ReplicateOperation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateFileStream",
			Handler:       _FileTransferService_CreateFileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AppendFileStream",
			Handler:       _FileTransferService_AppendFileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFileStream",
			Handler:       _FileTransferService_GetFileStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReplicateOperationStream",
			Handler:       _FileTransferService_ReplicateOperationStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/filetransfer.proto",
}
