// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: coordination.proto

package coordination

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_coordination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HealthCheckRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HealthCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Healthy           bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveFiles       int32                  `protobuf:"varint,2,opt,name=active_files,json=activeFiles,proto3" json:"active_files,omitempty"`
	NodeId            string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ServicesAvailable []string               `protobuf:"bytes,5,rep,name=services_available,json=servicesAvailable,proto3" json:"services_available,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_coordination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetActiveFiles() int32 {
	if x != nil {
		return x.ActiveFiles
	}
	return 0
}

func (x *HealthCheckResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetServicesAvailable() []string {
	if x != nil {
		return x.ServicesAvailable
	}
	return nil
}

// Node status messages
type NodeStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestingNodeId string                 `protobuf:"bytes,1,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_coordination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{2}
}

func (x *NodeStatusRequest) GetRequestingNodeId() string {
	if x != nil {
		return x.RequestingNodeId
	}
	return ""
}

type NodeStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsHealthy            bool                   `protobuf:"varint,2,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	TotalFiles           int64                  `protobuf:"varint,3,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	StorageUsedBytes     int64                  `protobuf:"varint,4,opt,name=storage_used_bytes,json=storageUsedBytes,proto3" json:"storage_used_bytes,omitempty"`
	LastUpdatedTimestamp int64                  `protobuf:"varint,5,opt,name=last_updated_timestamp,json=lastUpdatedTimestamp,proto3" json:"last_updated_timestamp,omitempty"`
	ReplicaNodes         []string               `protobuf:"bytes,6,rep,name=replica_nodes,json=replicaNodes,proto3" json:"replica_nodes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_coordination_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatusResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *NodeStatusResponse) GetTotalFiles() int64 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *NodeStatusResponse) GetStorageUsedBytes() int64 {
	if x != nil {
		return x.StorageUsedBytes
	}
	return 0
}

func (x *NodeStatusResponse) GetLastUpdatedTimestamp() int64 {
	if x != nil {
		return x.LastUpdatedTimestamp
	}
	return 0
}

func (x *NodeStatusResponse) GetReplicaNodes() []string {
	if x != nil {
		return x.ReplicaNodes
	}
	return nil
}

// File coordination messages
type ListFilesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientId         int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestingNodeId string                 `protobuf:"bytes,2,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_coordination_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{4}
}

func (x *ListFilesRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ListFilesRequest) GetRequestingNodeId() string {
	if x != nil {
		return x.RequestingNodeId
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filenames     []string               `protobuf:"bytes,1,rep,name=filenames,proto3" json:"filenames,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_coordination_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilesResponse) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

func (x *ListFilesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Merge operations (coordination only, no data transfer)
type MergeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Filename         string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ClientId         int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestingNodeId string                 `protobuf:"bytes,3,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:"requesting_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_coordination_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{6}
}

func (x *MergeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MergeRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *MergeRequest) GetRequestingNodeId() string {
	if x != nil {
		return x.RequestingNodeId
	}
	return ""
}

type MergeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FinalVersion  int64                  `protobuf:"varint,3,opt,name=final_version,json=finalVersion,proto3" json:"final_version,omitempty"`
	InvolvedNodes []string               `protobuf:"bytes,4,rep,name=involved_nodes,json=involvedNodes,proto3" json:"involved_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeResponse) Reset() {
	*x = MergeResponse{}
	mi := &file_coordination_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResponse) ProtoMessage() {}

func (x *MergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResponse.ProtoReflect.Descriptor instead.
func (*MergeResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{7}
}

func (x *MergeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MergeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MergeResponse) GetFinalVersion() int64 {
	if x != nil {
		return x.FinalVersion
	}
	return 0
}

func (x *MergeResponse) GetInvolvedNodes() []string {
	if x != nil {
		return x.InvolvedNodes
	}
	return nil
}

var File_coordination_proto protoreflect.FileDescriptor

const file_coordination_proto_rawDesc = "" +
	"\n" +
	"\x12coordination.proto\x12\x05hydfs\"O\n" +
	"\x12HealthCheckRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xc1\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\factive_files\x18\x02 \x01(\x05R\vactiveFiles\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12-\n" +
	"\x12services_available\x18\x05 \x03(\tR\x11servicesAvailable\"A\n" +
	"\x11NodeStatusRequest\x12,\n" +
	"\x12requesting_node_id\x18\x01 \x01(\tR\x10requestingNodeId\"\xf6\x01\n" +
	"\x12NodeStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x02 \x01(\bR\tisHealthy\x12\x1f\n" +
	"\vtotal_files\x18\x03 \x01(\x03R\n" +
	"totalFiles\x12,\n" +
	"\x12storage_used_bytes\x18\x04 \x01(\x03R\x10storageUsedBytes\x124\n" +
	"\x16last_updated_timestamp\x18\x05 \x01(\x03R\x14lastUpdatedTimestamp\x12#\n" +
	"\rreplica_nodes\x18\x06 \x03(\tR\freplicaNodes\"]\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12,\n" +
	"\x12requesting_node_id\x18\x02 \x01(\tR\x10requestingNodeId\"R\n" +
	"\x11ListFilesResponse\x12\x1c\n" +
	"\tfilenames\x18\x01 \x03(\tR\tfilenames\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"u\n" +
	"\fMergeRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12,\n" +
	"\x12requesting_node_id\x18\x03 \x01(\tR\x10requestingNodeId\"\x8b\x01\n" +
	"\rMergeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rfinal_version\x18\x03 \x01(\x03R\ffinalVersion\x12%\n" +
	"\x0einvolved_nodes\x18\x04 \x03(\tR\rinvolvedNodes2\x99\x02\n" +
	"\x13CoordinationService\x12D\n" +
	"\vHealthCheck\x12\x19.hydfs.HealthCheckRequest\x1a\x1a.hydfs.HealthCheckResponse\x12D\n" +
	"\rGetNodeStatus\x12\x18.hydfs.NodeStatusRequest\x1a\x19.hydfs.NodeStatusResponse\x12>\n" +
	"\tListFiles\x12\x17.hydfs.ListFilesRequest\x1a\x18.hydfs.ListFilesResponse\x126\n" +
	"\tMergeFile\x12\x13.hydfs.MergeRequest\x1a\x14.hydfs.MergeResponseB Z\x1ehydfs/protoBuilds/coordinationb\x06proto3"

var (
	file_coordination_proto_rawDescOnce sync.Once
	file_coordination_proto_rawDescData []byte
)

func file_coordination_proto_rawDescGZIP() []byte {
	file_coordination_proto_rawDescOnce.Do(func() {
		file_coordination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordination_proto_rawDesc), len(file_coordination_proto_rawDesc)))
	})
	return file_coordination_proto_rawDescData
}

var file_coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_coordination_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: hydfs.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: hydfs.HealthCheckResponse
	(*NodeStatusRequest)(nil),   // 2: hydfs.NodeStatusRequest
	(*NodeStatusResponse)(nil),  // 3: hydfs.NodeStatusResponse
	(*ListFilesRequest)(nil),    // 4: hydfs.ListFilesRequest
	(*ListFilesResponse)(nil),   // 5: hydfs.ListFilesResponse
	(*MergeRequest)(nil),        // 6: hydfs.MergeRequest
	(*MergeResponse)(nil),       // 7: hydfs.MergeResponse
}
var file_coordination_proto_depIdxs = []int32{
	0, // 0: hydfs.CoordinationService.HealthCheck:input_type -> hydfs.HealthCheckRequest
	2, // 1: hydfs.CoordinationService.GetNodeStatus:input_type -> hydfs.NodeStatusRequest
	4, // 2: hydfs.CoordinationService.ListFiles:input_type -> hydfs.ListFilesRequest
	6, // 3: hydfs.CoordinationService.MergeFile:input_type -> hydfs.MergeRequest
	1, // 4: hydfs.CoordinationService.HealthCheck:output_type -> hydfs.HealthCheckResponse
	3, // 5: hydfs.CoordinationService.GetNodeStatus:output_type -> hydfs.NodeStatusResponse
	5, // 6: hydfs.CoordinationService.ListFiles:output_type -> hydfs.ListFilesResponse
	7, // 7: hydfs.CoordinationService.MergeFile:output_type -> hydfs.MergeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coordination_proto_init() }
func file_coordination_proto_init() {
	if File_coordination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordination_proto_rawDesc), len(file_coordination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordination_proto_goTypes,
		DependencyIndexes: file_coordination_proto_depIdxs,
		MessageInfos:      file_coordination_proto_msgTypes,
	}.Build()
	File_coordination_proto = out.File
	file_coordination_proto_goTypes = nil
	file_coordination_proto_depIdxs = nil
}
