// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: fileservice.proto

package fileservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileService handles inter-node file operations
// Operation type for all file operations
type OperationType int32

const (
	OperationType_CREATE OperationType = 0
	OperationType_APPEND OperationType = 1
	OperationType_DELETE OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "CREATE",
		1: "APPEND",
		2: "DELETE",
	}
	OperationType_value = map[string]int32{
		"CREATE": 0,
		"APPEND": 1,
		"DELETE": 2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_fileservice_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_fileservice_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{0}
}

type FileMetadata_FileType int32

const (
	FileMetadata_SELF     FileMetadata_FileType = 0
	FileMetadata_REPLICA1 FileMetadata_FileType = 1
	FileMetadata_REPLICA2 FileMetadata_FileType = 2
)

// Enum value maps for FileMetadata_FileType.
var (
	FileMetadata_FileType_name = map[int32]string{
		0: "SELF",
		1: "REPLICA1",
		2: "REPLICA2",
	}
	FileMetadata_FileType_value = map[string]int32{
		"SELF":     0,
		"REPLICA1": 1,
		"REPLICA2": 2,
	}
)

func (x FileMetadata_FileType) Enum() *FileMetadata_FileType {
	p := new(FileMetadata_FileType)
	*p = x
	return p
}

func (x FileMetadata_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileMetadata_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_fileservice_proto_enumTypes[1].Descriptor()
}

func (FileMetadata_FileType) Type() protoreflect.EnumType {
	return &file_fileservice_proto_enumTypes[1]
}

func (x FileMetadata_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileMetadata_FileType.Descriptor instead.
func (FileMetadata_FileType) EnumDescriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{0, 0}
}

// File metadata message
type FileMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Filename        string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	LastModified    int64                  `protobuf:"varint,2,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Hash            string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Location        string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Type            FileMetadata_FileType  `protobuf:"varint,5,opt,name=type,proto3,enum=hydfs.FileMetadata_FileType" json:"type,omitempty"`
	LastOperationId int64                  `protobuf:"varint,6,opt,name=last_operation_id,json=lastOperationId,proto3" json:"last_operation_id,omitempty"`
	Size            int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_fileservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *FileMetadata) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileMetadata) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *FileMetadata) GetType() FileMetadata_FileType {
	if x != nil {
		return x.Type
	}
	return FileMetadata_SELF
}

func (x *FileMetadata) GetLastOperationId() int64 {
	if x != nil {
		return x.LastOperationId
	}
	return 0
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// File transfer messages for streaming
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_fileservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SendFileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HydfsFilename string                 `protobuf:"bytes,1,opt,name=hydfs_filename,json=hydfsFilename,proto3" json:"hydfs_filename,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OperationType OperationType          `protobuf:"varint,3,opt,name=operation_type,json=operationType,proto3,enum=hydfs.OperationType" json:"operation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileMetadata) Reset() {
	*x = SendFileMetadata{}
	mi := &file_fileservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileMetadata) ProtoMessage() {}

func (x *SendFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileMetadata.ProtoReflect.Descriptor instead.
func (*SendFileMetadata) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{2}
}

func (x *SendFileMetadata) GetHydfsFilename() string {
	if x != nil {
		return x.HydfsFilename
	}
	return ""
}

func (x *SendFileMetadata) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SendFileMetadata) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_CREATE
}

type SendFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*SendFileRequest_SendFileMetadata
	//	*SendFileRequest_Chunk
	Data          isSendFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_fileservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{3}
}

func (x *SendFileRequest) GetData() isSendFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendFileRequest) GetSendFileMetadata() *SendFileMetadata {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_SendFileMetadata); ok {
			return x.SendFileMetadata
		}
	}
	return nil
}

func (x *SendFileRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isSendFileRequest_Data interface {
	isSendFileRequest_Data()
}

type SendFileRequest_SendFileMetadata struct {
	SendFileMetadata *SendFileMetadata `protobuf:"bytes,1,opt,name=sendFileMetadata,proto3,oneof"` // First message in stream
}

type SendFileRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // Subsequent messages
}

func (*SendFileRequest_SendFileMetadata) isSendFileRequest_Data() {}

func (*SendFileRequest_Chunk) isSendFileRequest_Data() {}

type SendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResponse) Reset() {
	*x = SendFileResponse{}
	mi := &file_fileservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResponse) ProtoMessage() {}

func (x *SendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResponse.ProtoReflect.Descriptor instead.
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{4}
}

func (x *SendFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendReplicaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*SendReplicaRequest_Metadata
	//	*SendReplicaRequest_Chunk
	Data          isSendReplicaRequest_Data `protobuf_oneof:"data"`
	OperationType OperationType             `protobuf:"varint,3,opt,name=operation_type,json=operationType,proto3,enum=hydfs.OperationType" json:"operation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReplicaRequest) Reset() {
	*x = SendReplicaRequest{}
	mi := &file_fileservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReplicaRequest) ProtoMessage() {}

func (x *SendReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReplicaRequest.ProtoReflect.Descriptor instead.
func (*SendReplicaRequest) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{5}
}

func (x *SendReplicaRequest) GetData() isSendReplicaRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendReplicaRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*SendReplicaRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *SendReplicaRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Data.(*SendReplicaRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *SendReplicaRequest) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_CREATE
}

type isSendReplicaRequest_Data interface {
	isSendReplicaRequest_Data()
}

type SendReplicaRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // First message in stream
}

type SendReplicaRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // Subsequent messages
}

func (*SendReplicaRequest_Metadata) isSendReplicaRequest_Data() {}

func (*SendReplicaRequest_Chunk) isSendReplicaRequest_Data() {}

type SendReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReplicaResponse) Reset() {
	*x = SendReplicaResponse{}
	mi := &file_fileservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReplicaResponse) ProtoMessage() {}

func (x *SendReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReplicaResponse.ProtoReflect.Descriptor instead.
func (*SendReplicaResponse) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{6}
}

func (x *SendReplicaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendReplicaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_fileservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetFileRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_fileservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetFileResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_fileservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{9}
}

func (x *ListFilesRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filenames     []string               `protobuf:"bytes,1,rep,name=filenames,proto3" json:"filenames,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Added to match implementation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_fileservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesResponse) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

func (x *ListFilesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Merge operations
type MergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_fileservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{11}
}

func (x *MergeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *MergeRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type MergeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FinalVersion  int64                  `protobuf:"varint,3,opt,name=final_version,json=finalVersion,proto3" json:"final_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeResponse) Reset() {
	*x = MergeResponse{}
	mi := &file_fileservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeResponse) ProtoMessage() {}

func (x *MergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeResponse.ProtoReflect.Descriptor instead.
func (*MergeResponse) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{12}
}

func (x *MergeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MergeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MergeResponse) GetFinalVersion() int64 {
	if x != nil {
		return x.FinalVersion
	}
	return 0
}

// Health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_fileservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveFiles   int32                  `protobuf:"varint,2,opt,name=active_files,json=activeFiles,proto3" json:"active_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_fileservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fileservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_fileservice_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetActiveFiles() int32 {
	if x != nil {
		return x.ActiveFiles
	}
	return 0
}

var File_fileservice_proto protoreflect.FileDescriptor

const file_fileservice_proto_rawDesc = "" +
	"\n" +
	"\x11fileservice.proto\x12\x05hydfs\"\xa3\x02\n" +
	"\fFileMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12#\n" +
	"\rlast_modified\x18\x02 \x01(\x03R\flastModified\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x120\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1c.hydfs.FileMetadata.FileTypeR\x04type\x12*\n" +
	"\x11last_operation_id\x18\x06 \x01(\x03R\x0flastOperationId\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\"0\n" +
	"\bFileType\x12\b\n" +
	"\x04SELF\x10\x00\x12\f\n" +
	"\bREPLICA1\x10\x01\x12\f\n" +
	"\bREPLICA2\x10\x02\"=\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x93\x01\n" +
	"\x10SendFileMetadata\x12%\n" +
	"\x0ehydfs_filename\x18\x01 \x01(\tR\rhydfsFilename\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12;\n" +
	"\x0eoperation_type\x18\x03 \x01(\x0e2\x14.hydfs.OperationTypeR\roperationType\"\x8a\x01\n" +
	"\x0fSendFileRequest\x12E\n" +
	"\x10sendFileMetadata\x18\x01 \x01(\v2\x17.hydfs.SendFileMetadataH\x00R\x10sendFileMetadata\x12(\n" +
	"\x05chunk\x18\x02 \x01(\v2\x10.hydfs.FileChunkH\x00R\x05chunkB\x06\n" +
	"\x04data\"B\n" +
	"\x10SendFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb6\x01\n" +
	"\x12SendReplicaRequest\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.hydfs.FileMetadataH\x00R\bmetadata\x12(\n" +
	"\x05chunk\x18\x02 \x01(\v2\x10.hydfs.FileChunkH\x00R\x05chunk\x12;\n" +
	"\x0eoperation_type\x18\x03 \x01(\x0e2\x14.hydfs.OperationTypeR\roperationTypeB\x06\n" +
	"\x04data\"E\n" +
	"\x13SendReplicaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\x0eGetFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\"o\n" +
	"\x0fGetFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"/\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\"R\n" +
	"\x11ListFilesResponse\x12\x1c\n" +
	"\tfilenames\x18\x01 \x03(\tR\tfilenames\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"G\n" +
	"\fMergeRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\"d\n" +
	"\rMergeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rfinal_version\x18\x03 \x01(\x03R\ffinalVersion\"1\n" +
	"\x12HealthCheckRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\"R\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\factive_files\x18\x02 \x01(\x05R\vactiveFiles*3\n" +
	"\rOperationType\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06APPEND\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\x88\x03\n" +
	"\vFileService\x12=\n" +
	"\bSendFile\x12\x16.hydfs.SendFileRequest\x1a\x17.hydfs.SendFileResponse(\x01\x12F\n" +
	"\vSendReplica\x12\x19.hydfs.SendReplicaRequest\x1a\x1a.hydfs.SendReplicaResponse(\x01\x124\n" +
	"\aGetFile\x12\x15.hydfs.GetFileRequest\x1a\x10.hydfs.FileChunk0\x01\x12>\n" +
	"\tListFiles\x12\x17.hydfs.ListFilesRequest\x1a\x18.hydfs.ListFilesResponse\x126\n" +
	"\tMergeFile\x12\x13.hydfs.MergeRequest\x1a\x14.hydfs.MergeResponse\x12D\n" +
	"\vHealthCheck\x12\x19.hydfs.HealthCheckRequest\x1a\x1a.hydfs.HealthCheckResponseB\x1fZ\x1dhydfs/protoBuilds/fileserviceb\x06proto3"

var (
	file_fileservice_proto_rawDescOnce sync.Once
	file_fileservice_proto_rawDescData []byte
)

func file_fileservice_proto_rawDescGZIP() []byte {
	file_fileservice_proto_rawDescOnce.Do(func() {
		file_fileservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileservice_proto_rawDesc), len(file_fileservice_proto_rawDesc)))
	})
	return file_fileservice_proto_rawDescData
}

var file_fileservice_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fileservice_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_fileservice_proto_goTypes = []any{
	(OperationType)(0),          // 0: hydfs.OperationType
	(FileMetadata_FileType)(0),  // 1: hydfs.FileMetadata.FileType
	(*FileMetadata)(nil),        // 2: hydfs.FileMetadata
	(*FileChunk)(nil),           // 3: hydfs.FileChunk
	(*SendFileMetadata)(nil),    // 4: hydfs.SendFileMetadata
	(*SendFileRequest)(nil),     // 5: hydfs.SendFileRequest
	(*SendFileResponse)(nil),    // 6: hydfs.SendFileResponse
	(*SendReplicaRequest)(nil),  // 7: hydfs.SendReplicaRequest
	(*SendReplicaResponse)(nil), // 8: hydfs.SendReplicaResponse
	(*GetFileRequest)(nil),      // 9: hydfs.GetFileRequest
	(*GetFileResponse)(nil),     // 10: hydfs.GetFileResponse
	(*ListFilesRequest)(nil),    // 11: hydfs.ListFilesRequest
	(*ListFilesResponse)(nil),   // 12: hydfs.ListFilesResponse
	(*MergeRequest)(nil),        // 13: hydfs.MergeRequest
	(*MergeResponse)(nil),       // 14: hydfs.MergeResponse
	(*HealthCheckRequest)(nil),  // 15: hydfs.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 16: hydfs.HealthCheckResponse
}
var file_fileservice_proto_depIdxs = []int32{
	1,  // 0: hydfs.FileMetadata.type:type_name -> hydfs.FileMetadata.FileType
	0,  // 1: hydfs.SendFileMetadata.operation_type:type_name -> hydfs.OperationType
	4,  // 2: hydfs.SendFileRequest.sendFileMetadata:type_name -> hydfs.SendFileMetadata
	3,  // 3: hydfs.SendFileRequest.chunk:type_name -> hydfs.FileChunk
	2,  // 4: hydfs.SendReplicaRequest.metadata:type_name -> hydfs.FileMetadata
	3,  // 5: hydfs.SendReplicaRequest.chunk:type_name -> hydfs.FileChunk
	0,  // 6: hydfs.SendReplicaRequest.operation_type:type_name -> hydfs.OperationType
	5,  // 7: hydfs.FileService.SendFile:input_type -> hydfs.SendFileRequest
	7,  // 8: hydfs.FileService.SendReplica:input_type -> hydfs.SendReplicaRequest
	9,  // 9: hydfs.FileService.GetFile:input_type -> hydfs.GetFileRequest
	11, // 10: hydfs.FileService.ListFiles:input_type -> hydfs.ListFilesRequest
	13, // 11: hydfs.FileService.MergeFile:input_type -> hydfs.MergeRequest
	15, // 12: hydfs.FileService.HealthCheck:input_type -> hydfs.HealthCheckRequest
	6,  // 13: hydfs.FileService.SendFile:output_type -> hydfs.SendFileResponse
	8,  // 14: hydfs.FileService.SendReplica:output_type -> hydfs.SendReplicaResponse
	3,  // 15: hydfs.FileService.GetFile:output_type -> hydfs.FileChunk
	12, // 16: hydfs.FileService.ListFiles:output_type -> hydfs.ListFilesResponse
	14, // 17: hydfs.FileService.MergeFile:output_type -> hydfs.MergeResponse
	16, // 18: hydfs.FileService.HealthCheck:output_type -> hydfs.HealthCheckResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_fileservice_proto_init() }
func file_fileservice_proto_init() {
	if File_fileservice_proto != nil {
		return
	}
	file_fileservice_proto_msgTypes[3].OneofWrappers = []any{
		(*SendFileRequest_SendFileMetadata)(nil),
		(*SendFileRequest_Chunk)(nil),
	}
	file_fileservice_proto_msgTypes[5].OneofWrappers = []any{
		(*SendReplicaRequest_Metadata)(nil),
		(*SendReplicaRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileservice_proto_rawDesc), len(file_fileservice_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileservice_proto_goTypes,
		DependencyIndexes: file_fileservice_proto_depIdxs,
		EnumInfos:         file_fileservice_proto_enumTypes,
		MessageInfos:      file_fileservice_proto_msgTypes,
	}.Build()
	File_fileservice_proto = out.File
	file_fileservice_proto_goTypes = nil
	file_fileservice_proto_depIdxs = nil
}
